// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	var this1 = Math.max(-273.18,0);
	var waterfreezeC = this1;
	console.log("water freezes at " + waterfreezeC + " degrees Celcius.");
	var this2 = Math.max(-459.67,waterfreezeC / 5 * 9 + 32);
	var waterfreezeF = this2;
	console.log("water freezes at " + waterfreezeF + " degrees Fahrenheit");
	var run_time = Math.floor(new Date().getTime() / 1000);
	var age = run_time - 1518639181;
	console.log("Right now is's " + run_time + ", and this build is " + age + " seconds old ");
};
Main.main();
})();
